"""first_table_added

Revision ID: 1fb5d55e549a
Revises: 
Create Date: 2026-02-15 15:05:13.773271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb5d55e549a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_rules',
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('algorithm', sa.Enum('FIXED_WINDOW', 'SLIDING_WINDOW', 'SLIDING_LOG', 'TOKEN_BUCKET', name='ratelimitalgorithmoption'), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('key_type', sa.Enum('IP', 'USER', 'API_KEY', 'GLOBAL', name='ratelimitkeyoption'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_rules_path'), 'rate_limit_rules', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_rules_path'), table_name='rate_limit_rules')
    op.drop_table('rate_limit_rules')
    # ### end Alembic commands ###
